### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by BaseMax** [stickyPiston/roblang#1]
Dear Vonk

```
[max@workstation build]$ ./roblang 

[max@workstation build]$ ./roblang --help
Segmentation fault (core dumped)

[max@workstation build]$ ./roblang --version
Segmentation fault (core dumped)

[max@workstation build]$ ./roblang ../examples/goal.rob 
Segmentation fault (core dumped)

[max@workstation build]$ ./roblang ../examples/current.rob 
Written bitcode to out.bc!
```

**Comment by BaseMax** [comment]
Can I have your Email address, I think we can work together in related Compiler project.

Best;

**Comment by stickyPiston** [comment]
Hi BaseMax,

This project is still very much under construction, the behaviour of the executable you sent is completely expected. `goal.rob` is not supposed to be compiled (it's a file i refer to see the complete syntax), and `--version` and `--help` are not implemented (i will implement them in a later stage).

I'm glad, however, that you show interest in the project. Thanks for the heads up!

**Comment by BaseMax** [comment]
Thank you for your message.

I'm working on compiler, If you are interested in this field. Maybe we can help to each other and work on a common compiler. I am eager to cooperate. If you would like and agree, please DM and E-mail me.

Best Wishes.
